tags/openvolunteer_v0.2/urls.py
"""
    ---------------------------------------------------------------------------

                               OpenVolunteer
                     Copyright 2009, Ludovic Rivallain

    ---------------------------------------------------------------------------
    This file is part of OpenVolunteer.

    OpenVolunteer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenVolunteer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenVolunteer.  If not, see <http://www.gnu.org/licenses/>.
    ---------------------------------------------------------------------------
"""
from ovsettings import OPENVOLUNTEER_APP_PREFIX, OPENVOLUNTEER_SYSTEM_ROOT
from django.conf.urls.defaults import *
from django.contrib.comments import urls


urlpatterns = patterns(OPENVOLUNTEER_APP_PREFIX + 'views',
    # WELCOME view
    (r'^$', 'index'),

    # VOLUNTEERS
    # search
    (r'^volunteer/$','volunteer_index'),
    # view
    (r'^volunteer/(?P<volunteer_id>\d+)/$', 'volunteer_details'),
    # vcard generation
    (r'^volunteer/vcard/(?P<volunteer_id>\d+)/$', 'volunteer_vcard'),
    # add
    (r'^volunteer/add/$','volunteer_add'),
    # delete
    (r'^volunteer/delete/(?P<volunteer_id>\d+)/$', 'volunteer_delete'),
    # edit
    (r'^volunteer/edit/(?P<volunteer_id>\d+)/$', 'volunteer_edit'),
    # lists generator
    (r'^volunteer/list/$','list_volunteer_index'),

    # EVENTS
    # search
    (r'^event/$', 'event_index'),
    # view
    (r'^event/(?P<event_id>\d+)/$', 'event_details'),
    # add
    (r'^event/add/$', 'event_add'),
    # delete
    (r'^event/delete/(?P<event_id>\d+)/$', 'event_delete'),
    # edit
    (r'^event/edit/(?P<event_id>\d+)/$', 'event_edit'),
    # csv export
    (r'^event/csv/(?P<event_id>\d+)/$', 'event_csv'),

    # NEEDS
    # add
    (r'^event/need/add/(?P<event_id>\d+)/$', 'event_need_add'),
    # delete
    (r'^event/need/delete/(?P<need_id>\d+)/$', 'event_need_delete'),
    #edit
    (r'^event/need/edit/(?P<need_id>\d+)/$', 'event_need_edit'),

    # ANSWERS views and search tool
    # search and view (all answer for an event)
    (r'^answer/$','answer_index'),
    # view (ok and unknow)
    (r'^answer/positive/(?P<event_id>\d+)/$', 'answer_positives'),
    (r'^answer/unknown/(?P<event_id>\d+)/$', 'answer_tocontact'),
    # add (from event and from unknow answers list
    (r'^event/answer/add/(?P<event_id>\d+)/$', 'event_answer_add'),
    (r'^event/answer/add/(?P<event_id>\d+)/(?P<volunteer_id>\d+)/$', 'event_answer_add'),
    # delete
    (r'^event/answer/delete/(?P<answer_id>\d+)/$', 'event_answer_delete'),
    # edit
    (r'^event/answer/edit/(?P<answer_id>\d+)/$', 'event_answer_edit'),

    # JOBS
    # all job list
    (r'^job/$','job_index'),
    # add
    (r'^job/add/$','job_add'),
    # delete
    (r'^job/delete/(?P<job_id>\d+)/$','job_delete'),
    # edit
    (r'^job/edit/(?P<job_id>\d+)/$','job_edit'),

    # COMMENT
    # add
    (r'^event/comment/add/(?P<event_id>\d+)/$', 'event_comment_add'),
    # delete
    (r'^event/comment/delete/(?P<comment_id>\d+)/$', 'event_comment_delete'),

)

urlpatterns += patterns('',
    # Provide access to css files
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': OPENVOLUNTEER_SYSTEM_ROOT + '/static-files'}),
)

tags/openvolunteer_v0.2/models.py
#-*- coding: utf-8 -*-
"""
    ---------------------------------------------------------------------------

                               OpenVolunteer
                     Copyright 2009, Ludovic Rivallain

    ---------------------------------------------------------------------------
    This file is part of OpenVolunteer.

    OpenVolunteer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenVolunteer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenVolunteer.  If not, see <http://www.gnu.org/licenses/>.
    ---------------------------------------------------------------------------
"""
from ovsettings import *
from bigint import BigIntegerField

from django.db import models
from django.conf import settings
from django.template import defaultfilters

import os
import Image


def avatar_upload(instance, filename):
    """
    Upload the avatar to a file with volunteer name for a better
    organization

    instance : (object) - current volunteer
    filename : (string) - the title of uploaded file to get extension
    """
    # slugify name and firstname to avoid unicode problem
    slug_firstname = defaultfilters.slugify(instance.firstname)
    slug_name = defaultfilters.slugify(instance.name)

    # test if folder is available
    path  = settings.MEDIA_ROOT + OPENVOLUNTEER_APP_NAME + '/avatars/'
    if not os.path.exists(path):
        os.mkdir(path)

    # create complete filename and remove if existing
    file = "%s%s" % (slug_firstname, slug_name)
    type = filename.split('.')[len(filename.split('.'))-1]
    complete_filename = path + file + '.' + type
    if os.path.exists(complete_filename):
        os.remove(complete_filename)

    return complete_filename


class Volunteer(models.Model):
    """
    A volunteer is a personn linked to organization. Lot of
    informations are needed to contact him.
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, help_text='Nom (Une majuscule puis des minuscules)')
    firstname = models.CharField(max_length=100, help_text='Prénom (Une majuscule puis des minuscules)')
    email = models.EmailField(blank=True, null=True, help_text='Adresse email (yyyyyy@monfai.fr)')
    phone_home = models.CharField(max_length=20, blank=True, null=True,
                                  help_text='Téléphone fixe: 2 chiffres par deux chiffres, séparés par des espaces')
    phone_mobile = models.CharField(max_length=20, blank=True, null=True,
                                    help_text='Téléphone mobile: 2 chiffres par deux chiffres, séparés par des espaces')
    address = models.TextField(blank=True, null=True, help_text='Adresse')
    birthday = models.DateField(null=True, blank=True, help_text='Date de naissance (utiliser le calendrier)')
    birth_place = models.CharField(max_length=100, help_text='Lieu de naissance', blank=True, null=True)
    social_security_number = BigIntegerField(help_text='Numéro de sécurité sociale (15 chiffres)', blank=True, null=True)
    avatar = models.FileField(upload_to=avatar_upload,blank=True,help_text='Photo d\'identité')
    inscription_date = models.DateField(null=True, blank=True, auto_now_add=True,
                                        help_text='Date de la première inscription dans ce fichier.')
    comments = models.TextField(blank=True, null=True)
    ca_member = models.BooleanField('Membre du CA courant?', blank=True)

    class Meta:
        ordering = ('name','firstname')

    def __unicode__(self):
        return "%s %s" % (self.name, self.firstname)

    @models.permalink
    def get_absolute_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_details', (), {'volunteer_id': str(self.id)})

    @models.permalink
    def get_edit_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_edit', (), {'volunteer_id': str(self.id)})

    @models.permalink
    def get_delete_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_delete', (), {'volunteer_id': str(self.id)})

    @models.permalink
    def get_vcard_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_vcard', (), {'volunteer_id': str(self.id)})

    def get_photo_url(self):
        filename = self.avatar.path.split('/')[len(self.avatar.path.split('/'))-1]
        return "/media%s/avatars/%s" % (OPENVOLUNTEER_WEB_ROOT, filename)

    def save(self):
        super(Volunteer, self).save()
        if self.avatar:
            im = Image.open(self.avatar.name)
            size = 300, 300
            im.thumbnail(size, Image.ANTIALIAS)
            im.save(self.avatar.name)


def affiche_upload(instance, filename):
    """
    Upload the event poster to a file with event title for a better
    organization

    instance : (object) - current volunteer
    filename : (string) - the title of uploaded file to get extension
    """
    # test if folder is available
    path  = settings.MEDIA_ROOT + OPENVOLUNTEER_APP_NAME + '/affiches/'
    if not os.path.exists(path):
        os.mkdir(path)

    # create complete filename and remove if existing
    file = instance.stripped_title
    type = filename.split('.')[len(filename.split('.'))-1]
    complete_filename = path + file + '.' + type
    if os.path.exists(complete_filename):
        os.remove(complete_filename)

    return complete_filename

class Event(models.Model):
    """
    An event is just an event with date and place.
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,help_text='Nom de l\'événement')
    stripped_title = models.SlugField(db_index=True, max_length=255,
                                      help_text='Titre sans espaces et caractères spéciaux afin de composer une url.')
    date = models.DateField(help_text='Date de l\'événement')
    place = models.CharField(max_length=100,blank=True,help_text='Lieu de l\'événement')
    affiche = models.FileField(upload_to=affiche_upload,blank=True,help_text='Affiche de l\'événement')

    class Meta:
        ordering = ('-date',)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_details', (), {'event_id': str(self.id)})

    @models.permalink
    def get_edit_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_edit', (), {'event_id': str(self.id)})

    @models.permalink
    def get_delete_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_delete', (), {'event_id': str(self.id)})

    @models.permalink
    def get_comment_add_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_comment_add', (), {'event_id': str(self.id)})

    @models.permalink
    def get_need_add_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_need_add', (), {'event_id': str(self.id)})

    @models.permalink
    def get_answer_add_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_answer_add', (), {'event_id': str(self.id)})

    def get_answer_url(self):
        return "%s/answer/?v=&e=%d" % (OPENVOLUNTEER_WEB_ROOT, self.id)

    @models.permalink
    def get_positives_answer_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.answer_positives', (), {'event_id': str(self.id)})

    @models.permalink
    def get_unknown_answer_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.answer_tocontact', (), {'event_id': str(self.id)})

    def get_affiche_url(self):
        filename = self.affiche.path.split('/')[len(self.affiche.path.split('/'))-1]
        return "/media%s/affiches/%s" % (OPENVOLUNTEER_WEB_ROOT, filename)


class Job(models.Model):
    """
    A job is a for a volunteer a work to to during an event. Manager
    can add a description an link a job to a responsible.
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,help_text='Nom du poste')
    stripped_title = models.SlugField(db_index=True, max_length=255,
                                      help_text='Titre sans espaces et caractères spéciaux afin de com poser une url.')
    description = models.TextField(blank=True)
    boss = models.ManyToManyField(Volunteer,help_text='Responsables de commission',blank=True)

    class Meta:
        ordering = ('title',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return "%s/job/#job-%d" % (OPENVOLUNTEER_WEB_ROOT, self.id)

    @models.permalink
    def get_edit_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.job_edit', (), {'job_id': str(self.id)})

    @models.permalink
    def get_delete_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.job_delete', (), {'job_id': str(self.id)})


PRESENCE_CHOICES = (
    ('maybe', 'Peut-être'),
    ('yes', 'Oui'),
    ('no', 'Non'),
)


class Answer(models.Model):
    """
    An answer is the result of a request made by volunteer manager
    to see who will be present at an event. It's possible to assign
    a volunteer to a job in case of positive answer.
    """
    id = models.AutoField(primary_key=True)
    event = models.ForeignKey(Event,help_text='Évènement')
    volunteer = models.ForeignKey(Volunteer,help_text='Cliquez sur l\'icone pour chercher le bénévole')
    presence = models.CharField(max_length=5, choices=PRESENCE_CHOICES)
    job = models.ForeignKey(Job,null=True,blank=True,help_text='Poste')
    comments = models.TextField(blank=True,help_text='Commentaires')

tags/openvolunteer_v0.2/forms.py
#-*- coding: utf-8 -*-
"""
    ---------------------------------------------------------------------------

                               OpenVolunteer
                     Copyright 2009, Ludovic Rivallain

    ---------------------------------------------------------------------------
    This file is part of OpenVolunteer.

    OpenVolunteer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenVolunteer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenVolunteer.  If not, see <http://www.gnu.org/licenses/>.
    ---------------------------------------------------------------------------
"""
from django import forms
from models import PRESENCE_CHOICES


class VolunteerForm(forms.Form):
    name = forms.CharField(max_length=100)
    firstname = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    phone_home = forms.CharField(required=False, max_length=20)
    phone_mobile = forms.CharField(required=False, max_length=20)
    address = forms.CharField(required=False, widget=forms.Textarea)
    birth_place = forms.CharField(required=False, max_length=100)
    ca_member = forms.BooleanField(required=False)
    comments = forms.CharField(required=False, widget=forms.Textarea)
    avatar = forms.ImageField(required=False)
    delete_avatar = forms.BooleanField(required=False)


class EventForm(forms.Form):
    title = forms.CharField(max_length=100)
    place = forms.CharField(required=False, max_length=100)
    affiche = forms.ImageField(required=False)
    delete_affiche = forms.BooleanField(required=False)


class JobForm(forms.Form):
    title = forms.CharField(max_length=100)
    description = forms.CharField(required=False, widget=forms.Textarea)


class AnswerForm(forms.Form):
    presence = forms.ChoiceField(choices=PRESENCE_CHOICES)
    comments = forms.CharField(required=False, widget=forms.Textarea)

tags/openvolunteer_v0.2/templates/openvolunteer/answer_edit.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Édition d'une fiche{% endblock %}

{% block content %}
    <form method="POST" action="." class="edit-form center">
        <table class="centered">
            <tr>
                <th>Événement</th>
                <td class="required">{{ answer.event }}</td>
            </tr>
            <tr>
                <th>Bénévole</th>
                <td class="required">
                    <select id="id_volunteer" name="volunteer">
                        <option value="">----</option>
                        {{ sel_opts_vol|safe }}
                    </select>
                </td>
            </tr>
            <tr>
                <th>Poste</th>
                <td>
                    <select id="id_job" name="job">
                        <option value="">----</option>
                        {{ sel_opts_job|safe }}
                    </select>
                </td>
            </tr>
            <tr>
                <th>Présence</th>
                <td>
                    <select id="id_presence" name="presence">
                        <option value="maybe" {% ifequal answer.presence 'maybe'%}selected="selected"{% endifequal %}>Peut-être</option>
                        <option value="yes"   {% ifequal answer.presence 'yes'%}selected="selected"{% endifequal %}  >Oui</option>
                        <option value="no"    {% ifequal answer.presence 'no'%}selected="selected"{% endifequal %}   >Non</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th>Dernière demande</th>
                <script type="text/javascript">
                    function autoToday() {
                        var d=new Date();
                        document.getElementById('id_last_request_day').value = d.getDate();
                        document.getElementById('id_last_request_month').value = d.getMonth() + 1;
                        document.getElementById('id_last_request_year').value = d.getFullYear();
                    }
                </script>
                <td>
                    <input type="text" id="id_last_request_day" maxlength="2" size="2"
                           name="lastrequest_day" value='{{ answer.last_request|date:"d" }}'>
                    <input type="text" id="id_last_request_month" maxlength="2" size="2"
                           name="lastrequest_month" value='{{ answer.last_request|date:"m" }}'>
                    <input type="text" id="id_last_request_year" maxlength="4" size="4"
                           name="lastrequest_year" value='{{ answer.last_request|date:"Y" }}'>
                    <br>
                    (<a href="javascript:;" onclick="autoToday();">Aujourd'hui</a>)
                </td>
            </tr>
            <tr>
                <th>Commentaires</th>
                <td colspan="3">
                    <textarea id="id_comments" name="comments">{{ answer.comments }}</textarea>
                </td>
            </tr>
        </table>
        <p class="required">* Les champs marqués en <span>rouge</span> sont obligatoires.</p>
        <input type="submit" value="Enregistrer">
    </form>
{% endblock %}

{% block navigation %}
    <ul>
       </li><a href="{{ answer.event.get_answer_url }}" title="">Accéder à la liste des réponses</a></li>
    </ul>
{% endblock %}

tags/openvolunteer_v0.2/templates/openvolunteer/answer_index.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Chercher une(des) réponse(s){% endblock %}

{% block content %}
    <div>
        <form method="get" action="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/answer/">
            <fieldset>
                <p>
                    <select name="e">
                        {% for event in events %}
                            <option value="{{ event.id }}">{{ event.title }} ({{ event.date|date:"d F Y" }})</option>
                        {% endfor %}
                    </select><br>
                <p>
                    <input type="hidden" name="v" value="">
                    <input class="submit" type="submit" value="Rechercher">
                </p>
            </fieldset>
        </form>
    </div>
    <div class="search-results">
        {% if event %}
            <div class="answser-event">
                <h2><a href="{{ event.get_absolute_url }}" title="{{ event.title }}">{{ event.title }}</a></h2>
            ({{ event.date|date:"l d F Y" }} | {{ event.place }})</p>
            </div>
        {% endif %}

        {% if results %}
        <h3>Liste des bénévoles contactés pour cet événement:</h3>
        <table>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Téléphone fixe</th>
                <th>Mobile</th>
                <th>CA ?</th>
                <th>Poste</th>
            </tr>
            {% for result in results %}
                <tr class="{{ result.presence }}">
                    <td>{{ result.volunteer.name }}</td>
                    <td>{{ result.volunteer.firstname }}</td>
                    <td>
                        {% if result.volunteer.email %}
                            {{ result.volunteer.email }}&nbsp;
                            <a href="mailto:{{ result.volunteer.email }}" title="Envoyer un email">
                                <img src="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/icons/email.png" alt="mail" class="icon">
                            </a>
                        {% endif %}
                    </td>
                    <td>{{ result.volunteer.phone_home }}</td>
                    <td>{{ result.volunteer.phone_mobile }}</td>
                    <td style="text-align:center;">
                        {% if result.volunteer.ca_member %}
                            <img src="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/icons/yes.png" alt="oui" class="icon">
                        {% else %}
                            <img src="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/icons/no.png" alt="non" class="icon">
                        {% endif %}
                    </td>
                    <td>
                        {% if result.job %}
                            <a href="{{ result.job.get_absolute_url }}" title="Afficher la fiche du poste">{{ result.job }}</a>
                        {% endif %}
                    </td>
                    <td class="more">
                        <div id="dialog_conf_delete{{ result.id }}" title="Supprimer cette fiche?" style="text-align:center;">
                            <p>Êtes vous sûr de vouloir supprimer cette réponse?</p>
                            <p><a href="{{ result.get_delete_url }}" title="Confirmer l'opération">Confirmer</a></p>
                        </div>
                        <script>
                            $(function() {
                                $("#dialog_conf_delete{{ result.id }}").dialog({
                                    bgiframe: true,
                                    modal: true,
                                    autoOpen: false
                                });
                            });
                        </script>
                        <a href="{{ result.volunteer.get_absolute_url }}"
                           title="Consulter la fiche détaillée de {{ result.volunteer }}">
                           Bénévole
                        </a> |
                        <a href="{{ result.get_edit_url }}"
                           title="Modifer cette réponse">
                           Modifier
                        </a> |
                        <a href="javascript:;" onclick="$('#dialog_conf_delete{{ result.id }}').dialog('open');"
                           title="Supprimer cette réponse">
                           Supprimer
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="legend">
            <div class="legend-positive"><div></div>&nbsp;: Réponses positives</div>
            <div class="legend-negative"><div></div>&nbsp;: Réponses négatives</div>
            <div class="legend-maybe"   ><div></div>&nbsp;: Réponses "Peut-être"</div>
        </div>
        {% else %}
            <div class="search-error">
                {% if terms %}
                    <p>Le(s) terme(s) de recherche spécifié(s) – {{ terms }} – ne correspond(ent) à aucun document.</p>
                    <p>Suggestions :
                        <ul>
                            <li>Vérifiez l’orthographe des termes de recherche.</li>
                            <li>Essayez d'autres mots.</li>
                            <li>Utilisez des mots plus généraux.</li>
                        </ul>
                    </p>
                {% else %}
                    <h3>Obtenir la liste de toutes les réponses (positives et négatives) pour un évènement.</h3>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block navigation %}
    <ul>
        <li>
            <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/event/" title="Accéder à la liste des événements">
                Chercher un événement
            </a>
        </li>
        {% if event %}
            <li>
                <a href="{{ event.get_answer_add_url }}" title="Ajouter une réponse">
                    Ajouter une réponse
                </a>
            </li>
            <li>
                <a href="{{ event.get_absolute_url }}"
                   title="Modifier les informations de {{ volunter }}">
                   Voir la fiche de l'événement
                </a>
            </li>
            <li>
                <a href="{{ event.get_positives_answer_url }}"
                   title="Obtenir la liste des bénévoles présents à cet événement">
                   Obtenir la liste des bénévoles présents à cet événement
                </a>
            </li>
            <li>
                <a href="{{ event.get_unknown_answer_url }}"
                   title="Obtenir la liste des bénévoles non contactés pour cet événement">
                   Obtenir la liste des bénévoles non contactés pour cet événement
                </a>
            </li>
        {% endif %}
    </ul>
{% endblock %}

tags/openvolunteer_v0.2/templates/openvolunteer/event_edit.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Édition d'une fiche{% endblock %}

{% block content %}
    <form method="POST" action="." class="edit-form center" enctype="multipart/form-data">
        <table class="centered">
            <tr>
                <th>Titre</th>
                <td class="required">
                    <input type="text" id="id_title" name="title"
                           maxlength="100" value='{{ event.title }}'>
                </td>
            </tr>
            <tr>
                <th>Date</th>
                <td class="required">
                    <input type="text" id="id_date_day" maxlength="2" size="2"
                           name="date_day" value='{{ event.date|date:"d" }}'>
                    <input type="text" id="id_date_month" maxlength="2" size="2"
                           name="date_month" value='{{ event.date|date:"m" }}'>
                    <input type="text" id="id_birthday_year" maxlength="4" size="4"
                           name="date_year" value='{{ event.date|date:"Y" }}'>
                </td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>
                    <input type="text" id="id_place" name="place"
                           maxlength="100" value='{{ event.place }}'>
                </td>
            </tr>
            <tr>
                <th>Affiche</th>
                <td>
                    {{ form.affiche }}<br>
                    <input type="checkbox" id="id_delete_affiche" name="delete_affiche"><i>Supprimer l'affiche actuelle?</i>
                </td>
            </tr>
        </table>
        <p class="required">* Les champs marqués en <span>rouge</span> sont obligatoires.</p>
        <input type="submit" value="Enregistrer">
    </form>
{% endblock %}

{% block navigation %}
    <ul>
        {% if event %}
            <li><a href="{{ event.get_absolute_url }}" title="">Revenir à la fiche de l'événement</a></li>
        {% else %}
            <li><a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/event/" title="">Rechercher un événement</a></li>
        {% endif %}
    </ul>
{% endblock %}

tags/openvolunteer_v0.2/templates/openvolunteer/need_edit.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Édition d'une fiche{% endblock %}

{% block content %}
    <form method="POST" action="." class="edit-form center">
        <table class="centered">
            <tr>
                <th>Événement</th>
                <td>{{ need.event }}</td>
            </tr>
            <tr>
                <th>Poste</th>
                <td class="required">
                    <select id="id_job" name="job">
                        {{ sel_opts|safe }}
                    </select>
                </td>
            </tr>
            <tr>
                <th>Nombre de bénévoles</th>
                <td class="required">
                    <input type="text" id="id_number" name="number"
                           size="3" maxlength="3" value='{% if need.number %}{{ need.number }}{% endif %}'>
                </td>
            </tr>
        </table>
        <p class="required">* Les champs marqués en <span>rouge</span> sont obligatoires.</p>
        <input type="submit" value="Enregistrer">
    </form>
{% endblock %}

{% block navigation %}
    <ul>
        <li><a href="{{ need.event.get_absolute_url }}" title="">Revenir à la fiche de l'événement</a></li>
    </ul>
{% endblock %}