trunk/urls.py
"""
    ---------------------------------------------------------------------------

                               OpenVolunteer
                     Copyright 2009, Ludovic Rivallain

    ---------------------------------------------------------------------------
    This file is part of OpenVolunteer.

    OpenVolunteer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenVolunteer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenVolunteer.  If not, see <http://www.gnu.org/licenses/>.
    ---------------------------------------------------------------------------
"""
from ovsettings import OPENVOLUNTEER_APP_PREFIX, OPENVOLUNTEER_SYSTEM_ROOT
from django.conf.urls.defaults import *
from django.contrib.comments import urls


urlpatterns = patterns(OPENVOLUNTEER_APP_PREFIX + 'views',
    # WELCOME view
    (r'^$', 'index'),

    # VOLUNTEERS
    # search
    (r'^volunteer/$','volunteer_index'),
    # view
    (r'^volunteer/(?P<volunteer_id>\d+)/$', 'volunteer_details'),
    # vcard generation
    (r'^volunteer/vcard/(?P<volunteer_id>\d+)/$', 'volunteer_vcard'),
    # add
    (r'^volunteer/add/$','volunteer_add'),
    # delete
    (r'^volunteer/delete/(?P<volunteer_id>\d+)/$', 'volunteer_delete'),
    # edit
    (r'^volunteer/edit/(?P<volunteer_id>\d+)/$', 'volunteer_edit'),
    # lists generator
    (r'^volunteer/list/$','list_volunteer_index'),
    # lists generator by previous job
    (r'^volunteer/by-job/(?P<job_id>\d+)/$','volunteer_byjob'),

    # EVENTS
    # search
    (r'^event/$', 'event_index'),
    # view
    (r'^event/(?P<event_id>\d+)/$', 'event_details'),
    # add
    (r'^event/add/$', 'event_add'),
    # delete
    (r'^event/delete/(?P<event_id>\d+)/$', 'event_delete'),
    # edit
    (r'^event/edit/(?P<event_id>\d+)/$', 'event_edit'),
    # csv export
    (r'^event/csv/(?P<event_id>\d+)/$', 'event_csv'),

    # NEEDS
    # add
    (r'^need/add/(?P<event_id>\d+)/$', 'event_need_add'),
    # delete
    (r'^need/delete/(?P<need_id>\d+)/$', 'need_delete'),
    # edit
    (r'^need/edit/(?P<need_id>\d+)/$', 'need_edit'),
    # planning
    (r'^need/planning/(?P<need_id>\d+)/$', 'need_planning'),

    # ANSWERS
    # search and view (all answer for an event)
    (r'^answer/$','answer_index'),
    # view (ok and unknow)
    (r'^answer/positive/(?P<event_id>\d+)/$', 'answer_positives'),
    (r'^answer/unknown/(?P<event_id>\d+)/$', 'answer_tocontact'),
    # add (from event and from unknow answers list
    (r'^event/answer/add/(?P<event_id>\d+)/$', 'event_answer_add'),
    (r'^event/answer/add/(?P<event_id>\d+)/(?P<volunteer_id>\d+)/$', 'event_answer_add'),
    # delete
    (r'^event/answer/delete/(?P<answer_id>\d+)/$', 'event_answer_delete'),
    # edit
    (r'^event/answer/edit/(?P<answer_id>\d+)/$', 'event_answer_edit'),

    # JOBS
    # all job list
    (r'^job/$','job_index'),
    # add
    (r'^job/add/$','job_add'),
    # delete
    (r'^job/delete/(?P<job_id>\d+)/$','job_delete'),
    # edit
    (r'^job/edit/(?P<job_id>\d+)/$','job_edit'),

    # COMMENT
    # add
    (r'^event/comment/add/(?P<event_id>\d+)/$', 'event_comment_add'),
    # delete
    (r'^event/comment/delete/(?P<comment_id>\d+)/$', 'event_comment_delete'),

    # API
    (r'^api/volunteer/get/$','api_volunteer_get'),
#    (r'^api/event/get/$','api_event_get'),
)

urlpatterns += patterns('',
    # Provide access to css files
    (r'^files/(?P<path>.*)$', 'django.views.static.serve', {'document_root': OPENVOLUNTEER_SYSTEM_ROOT + '/static-files'}),
)

trunk/models.py
#-*- coding: utf-8 -*-
"""
    ---------------------------------------------------------------------------

                               OpenVolunteer
                     Copyright 2009, Ludovic Rivallain

    ---------------------------------------------------------------------------
    This file is part of OpenVolunteer.

    OpenVolunteer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenVolunteer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenVolunteer.  If not, see <http://www.gnu.org/licenses/>.
    ---------------------------------------------------------------------------
"""
from ovsettings import *

from django.db import models
from django.conf import settings
from django.template import defaultfilters

import os
import Image


def avatar_upload(instance, filename):
    """
    Upload the avatar to a file with volunteer name for a better
    organization

    instance : (object) - current volunteer
    filename : (string) - the title of uploaded file to get extension

    # Create a test volunteer
    >>> i = Volunteer.objects.create(name='Smith',firstname='David')

    # get complete filename
    >>> cfn = avatar_upload(i, 'toto.jpg')
    >>> print cfn.split('/')[len(cfn.split('/'))-1]
    davidsmith.jpg

    # get complete filename
    >>> cfn = avatar_upload(i, 'toto.png')
    >>> print cfn.split('/')[len(cfn.split('/'))-1]
    davidsmith.png

    >>> i.firstname = 'David Dude'
    >>> cfn = avatar_upload(i, 'toto.png')
    >>> print cfn.split('/')[len(cfn.split('/'))-1]
    david-dudesmith.png

    """
    # slugify name and firstname to avoid unicode problem
    slug_firstname = defaultfilters.slugify(instance.firstname)
    slug_name = defaultfilters.slugify(instance.name)

    # test if folder is available
    path  = settings.MEDIA_ROOT + OPENVOLUNTEER_APP_NAME + '/avatars/'
    if not os.path.exists(path):
        os.mkdir(path)

    # create complete filename and remove if existing
    file = "%s%s" % (slug_firstname, slug_name)
    type = filename.split('.')[len(filename.split('.'))-1]
    complete_filename = path + file + '.' + type
    if os.path.exists(complete_filename):
        os.remove(complete_filename)

    return complete_filename


class Volunteer(models.Model):
    """
    A volunteer is a personn linked to organization. Lot of
    informations are needed to contact him.
    """
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, help_text='Nom (Une majuscule puis des minuscules)')
    firstname = models.CharField(max_length=100, help_text='Prénom (Une majuscule puis des minuscules)')
    email = models.EmailField(blank=True, null=True, help_text='Adresse email (yyyyyy@monfai.fr)')
    phone_home = models.CharField(max_length=20, blank=True, null=True,
                                  help_text='Téléphone fixe: 2 chiffres par deux chiffres, séparés par des espaces')
    phone_mobile = models.CharField(max_length=20, blank=True, null=True,
                                    help_text='Téléphone mobile: 2 chiffres par deux chiffres, séparés par des espaces')
    address = models.TextField(blank=True, null=True, help_text='Adresse')
    birthday = models.DateField(null=True, blank=True, help_text='Date de naissance (utiliser le calendrier)')
    birth_place = models.CharField(max_length=100, help_text='Lieu de naissance', blank=True, null=True)
    social_security_number = models.BigIntegerField(help_text='Numéro de sécurité sociale (15 chiffres)', blank=True, null=True)
    avatar = models.FileField(upload_to=avatar_upload,blank=True,help_text='Photo d\'identité')
    inscription_date = models.DateField(null=True, blank=True, auto_now_add=True,
                                        help_text='Date de la première inscription dans ce fichier.')
    comments = models.TextField(blank=True, null=True)
    ca_member = models.BooleanField('Membre du CA courant?', blank=True)

    class Meta:
        ordering = ('name','firstname')

    def __unicode__(self):
        return "%s %s" % (self.name, self.firstname)

    @models.permalink
    def get_absolute_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_details', (), {'volunteer_id': str(self.id)})

    @models.permalink
    def get_edit_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_edit', (), {'volunteer_id': str(self.id)})

    @models.permalink
    def get_delete_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_delete', (), {'volunteer_id': str(self.id)})

    @models.permalink
    def get_vcard_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.volunteer_vcard', (), {'volunteer_id': str(self.id)})

    def get_photo_url(self):
        filename = self.avatar.path.split('/')[len(self.avatar.path.split('/'))-1]
        return "/media%s/avatars/%s" % (OPENVOLUNTEER_WEB_ROOT, filename)

    def save(self, *args, **kwargs):
        super(Volunteer, self).save(*args, **kwargs)
        if self.avatar:
            im = Image.open(self.avatar.name)
            size = 300, 300
            im.thumbnail(size, Image.ANTIALIAS)
            im.save(self.avatar.name)


def affiche_upload(instance, filename):
    """
    Upload the event poster to a file with event title for a better
    organization

    instance : (object) - current volunteer
    filename : (string) - the title of uploaded file to get extension

    # Create a test volunteer
    >>> from datetime import datetime
    >>> i = Event.objects.create(title='My super Event', date=datetime.now())
    >>> i.stripped_title = 'my-super-event'

    # get complete filename
    >>> cfn = affiche_upload(i, 'toto.jpg')
    >>> print cfn.split('/')[len(cfn.split('/'))-1]
    my-super-event.jpg

    # get complete filename
    >>> cfn = affiche_upload(i, 'toto.png')
    >>> print cfn.split('/')[len(cfn.split('/'))-1]
    my-super-event.png
    """
    # test if folder is available
    path  = settings.MEDIA_ROOT + OPENVOLUNTEER_APP_NAME + '/affiches/'
    if not os.path.exists(path):
        os.mkdir(path)

    # create complete filename and remove if existing
    file = instance.stripped_title
    type = filename.split('.')[len(filename.split('.'))-1]
    complete_filename = path + file + '.' + type
    if os.path.exists(complete_filename):
        os.remove(complete_filename)

    return complete_filename

class Event(models.Model):
    """
    An event is just an event with date and place.
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,help_text='Nom de l\'événement')
    stripped_title = models.SlugField(db_index=True, max_length=255,
                                      help_text='Titre sans espaces et caractères spéciaux afin de composer une url.')
    date = models.DateField(help_text='Date de l\'événement')
    place = models.CharField(max_length=100,blank=True,help_text='Lieu de l\'événement')
    affiche = models.FileField(upload_to=affiche_upload,blank=True,help_text='Affiche de l\'événement')

    class Meta:
        ordering = ('-date',)

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_details', (), {'event_id': str(self.id)})

    @models.permalink
    def get_edit_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_edit', (), {'event_id': str(self.id)})

    @models.permalink
    def get_delete_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_delete', (), {'event_id': str(self.id)})

    @models.permalink
    def get_comment_add_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_comment_add', (), {'event_id': str(self.id)})

    @models.permalink
    def get_need_add_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_need_add', (), {'event_id': str(self.id)})

    @models.permalink
    def get_answer_add_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.event_answer_add', (), {'event_id': str(self.id)})

    def get_answer_url(self):
        return "%s/answer/?v=&q=%d" % (OPENVOLUNTEER_WEB_ROOT, self.id)

    @models.permalink
    def get_positives_answer_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.answer_positives', (), {'event_id': str(self.id)})

    @models.permalink
    def get_unknown_answer_url(self):
        return (OPENVOLUNTEER_APP_PREFIX + 'views.answer_tocontact', (), {'event_id': str(self.id)})

    def get_affiche_url(self):
        filename = self.affiche.path.split('/')[len(self.affiche.path.split('/'))-1]
        return "/media%s/affiches/%s" % (OPENVOLUNTEER_WEB_ROOT, filename)

    def save(self, *args, **kwargs):
        super(Event, self).save(*args, **kwargs)
        if self.affiche:
            im = Image.open(self.affiche.name)
            size = 300, 300
            im.thumbnail(size, Image.ANTIALIAS)
            im.save(self.affiche.name)


class Job(models.Model):
    """
    A job is a for a volunteer a work to to during an event. Manager
    can add a description an link a job to a responsible.
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100,help_text='Nom du poste')
    stripped_title = models.SlugField(db_index=True, max_length=255,
                                      help_text='Titre sans espaces et caractères spéciaux afin de com poser une url.')
    description = models.TextField(blank=True)

tags/openvolunteer_v0.2/forms.py
#-*- coding: utf-8 -*-
"""
    ---------------------------------------------------------------------------

                               OpenVolunteer
                     Copyright 2009, Ludovic Rivallain

    ---------------------------------------------------------------------------
    This file is part of OpenVolunteer.

    OpenVolunteer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenVolunteer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenVolunteer.  If not, see <http://www.gnu.org/licenses/>.
    ---------------------------------------------------------------------------
"""
from django import forms
from models import PRESENCE_CHOICES


class VolunteerForm(forms.Form):
    name = forms.CharField(max_length=100)
    firstname = forms.CharField(max_length=100)
    email = forms.EmailField(required=False)
    phone_home = forms.CharField(required=False, max_length=20)
    phone_mobile = forms.CharField(required=False, max_length=20)
    address = forms.CharField(required=False, widget=forms.Textarea)
    birth_place = forms.CharField(required=False, max_length=100)
    ca_member = forms.BooleanField(required=False)
    comments = forms.CharField(required=False, widget=forms.Textarea)
    avatar = forms.ImageField(required=False)
    delete_avatar = forms.BooleanField(required=False)


class EventForm(forms.Form):
    title = forms.CharField(max_length=100)
    place = forms.CharField(required=False, max_length=100)
    affiche = forms.ImageField(required=False)
    delete_affiche = forms.BooleanField(required=False)


class JobForm(forms.Form):
    title = forms.CharField(max_length=100)
    description = forms.CharField(required=False, widget=forms.Textarea)


class AnswerForm(forms.Form):
    presence = forms.ChoiceField(choices=PRESENCE_CHOICES)
    comments = forms.CharField(required=False, widget=forms.Textarea)

templates/openvolunteer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
 "http://www.w3.org/TR/html4/strict.dtd">

<html lang="fr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{% block title %}OpenVolunteer {% endblock %}</title>
    <link rel="icon" type="image/png" href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/openvolunteer_favicon.png">
    <style type="text/css">
        @import url({{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/css/openvolunteer.css);
        @import url({{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/jquery/css/smoothness/jquery-ui.css);
        @import url({{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/css/autocomplete.css);
    </style>
    <script type="text/javascript" src="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/jquery/js/jquery.js"></script>
    <script type="text/javascript" src="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/jquery/js/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function() {
            $("#footer").dialog({
                bgiframe: true,
                height: 'auto',
                width: 400,
                modal: true,
                autoOpen: false
            });
        });
    </script>
</head>
<body class="openvolunteer">
    <div class="logo">
        <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/" title="Accueil">
            <img src="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/files/logo.png" alt="OpenVolunteer">
        </a>
    </div>
    <div class="registration">
        {% if user.is_authenticated %}
            Bonjour <a href="mailto:{{ user.email}}">
            {% if user.first_name and user.last_name %}
                {{ user.first_name }} {{ user.last_name }}</a>:
            {% else %}
                {{ user.username }}</a>:
            {% endif %}
            <a href="/accounts/logout/?next={{ settings.OPENVOLUNTEER_WEB_ROOT }}/" title="Se déconnecter">Déconnexion</a> |
            <a href="/admin/{{ settings.OPENVOLUNTEER_APP_NAME }}/" title="Accéder à l'interface d'administration d'OpenVolunteer">Administration</a>
        {% else %}
            <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/" title="Accéder à l'accueil">Accueil</a> |
            <a href="/accounts/login/?next={{ settings.OPENVOLUNTEER_WEB_ROOT }}/" title="Se connecter">Connexion</a>
        {% endif %}
        | <a href="javascript:;" onclick="$('#footer').dialog('open');" title="À propos d'OpenVolunteer">À propos</a>
    </div>
    <div class="menu">
        <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/"          title="Accéder à l'accueil">Accueil  </a> |
        <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/volunteer" title="Bénévoles"          >Bénévoles</a> |
        <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/event/"    title="Événements"         >Événement</a> |
        <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/answer/"   title="Réponses"           >Réponses </a> |
        <a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/job/"      title="Postes"             >Postes   </a>
    </div>
    <div class="shortcuts">
        {% block navigation %}{% endblock %}
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer" title="À propos d'OpenVolunteer !" class="center">
        <p>
            © 2008-2009 <a href="http://code.google.com/p/openvolunteer/">OpenVolunteer</a>
        </p>
        <p>
            Propulsé par <a href="http://djangoproject.com">Django</a>
        </p>
        <p>
            Publié sous <a href="http://www.gnu.org/licenses/gpl.html">Licence GNU/GPLv3</a>
        </p>
    </div>
</body>
</html>

templates/openvolunteer/event_edit.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Édition d'une fiche{% endblock %}

{% block content %}
    <form method="post" action="." class="edit-form center" enctype="multipart/form-data">{% csrf_token %}
        <table class="centered">
            <tr>
                <th>Titre</th>
                <td class="required">
                    <input type="text" id="id_title" name="title"
                           maxlength="100" value='{{ event.title }}'>
                </td>
            </tr>
            <tr>
                <th>Date</th>
                <td class="required">
                    <input type="text" id="id_date_day" maxlength="2" size="2"
                           name="date_day" value='{{ event.date|date:"d" }}'>
                    <input type="text" id="id_date_month" maxlength="2" size="2"
                           name="date_month" value='{{ event.date|date:"m" }}'>
                    <input type="text" id="id_birthday_year" maxlength="4" size="4"
                           name="date_year" value='{{ event.date|date:"Y" }}'>
                </td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>
                    <input type="text" id="id_place" name="place"
                           maxlength="100" value='{{ event.place }}'>
                </td>
            </tr>
            <tr>
                <th>Affiche</th>
                <td>
                    {{ form.affiche }}<br>
                    <input type="checkbox" id="id_delete_affiche" name="delete_affiche"><i>Supprimer l'affiche actuelle?</i>
                </td>
            </tr>
        </table>
        <p class="required">* Les champs marqués en <span>rouge</span> sont obligatoires.</p>
        <input type="submit" value="Enregistrer">
    </form>
{% endblock %}

{% block navigation %}
    <ul>
        {% if event %}
            <li><a href="{{ event.get_absolute_url }}" title="">Revenir à la fiche de l'événement</a></li>
        {% else %}
            <li><a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/event/" title="">Rechercher un événement</a></li>
        {% endif %}
    </ul>
{% endblock %}

templates/openvolunteer/job_edit.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Édition d'une fiche{% endblock %}

{% block content %}
    <form method="post" action="." class="edit-form center">{% csrf_token %}
        <table class="centered">
            <tr>
                <th>Titre</th>
                <td class="required">
                    <input type="text" id="id_title" name="title"
                           maxlength="100" value='{{ job.title }}'>
                </td>
            </tr>
            <tr>
                <th>Responsable(s)</th>
                <td>
                    <select multiple="multiple" id="id_boss" name="boss">
                        {{ sel_opts|safe }}
                    </select>
                </td>
            </tr>
            <tr>
                <th>Description</th>
                <td>
                    <textarea id="id_description" name="description">{{ job.description }}</textarea>
                </td>
            </tr>
        </table>
        <p class="required">* Les champs marqués en <span>rouge</span> sont obligatoires.</p>
        <input type="submit" value="Enregistrer">
    </form>
{% endblock %}

{% block navigation %}
    <ul>
        {% if job %}
            <li><a href="{{ job.get_absolute_url }}" title="">Revenir à la liste des postes.</a></li>
        {% else %}
            <li><a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/job/" title="">Revenir à la liste des postes</a></li>
        {% endif %}
    </ul>
{% endblock %}

templates/openvolunteer/volunteer_edit.html
{% extends "openvolunteer/base.html" %}

{% block title %}OpenVolunteer | Édition d'une fiche{% endblock %}

{% block content %}
    <form method="post" action="." class="edit-form center" enctype="multipart/form-data">{% csrf_token %}
        <table class="centered">
            <tr>
                <th>Nom</th>
                <td class="required">
                    <input type="text" id="id_name" name="name"
                           maxlength="100" value='{{ volunteer.name }}'>
                </td>
                <th>Prénom</th>
                <td class="required">
                    <input type="text" id="id_firstname" name="firstname"
                           maxlength="100" value='{{ volunteer.firstname }}'>
                </td>
            </tr>
            <tr>
                <th>Email</th>
                <td>
                    <input type="text" id="id_email" name="email"
                           maxlength="100" value='{{ volunteer.email }}'>
                </td>
                <th>Membre du CA?</th>
                <td>
                    <input type="checkbox" id="id_ca_member" name="ca_member"
                    {% if volunteer.ca_member %}checked{% endif %}>
                </td>
            </tr>
            <tr>
                <th>Téléphone fixe</th>
                <td>
                    <input type="text" id="id_phone_home" name="phone_home"
                           maxlength="20" value='{{ volunteer.phone_home }}'>
                </td>
                <th>Téléphone mobile</th>
                <td>
                    <input type="text" id="id_phone_mobile" name="phone_mobile"
                           maxlength="20" value='{{ volunteer.phone_mobile }}'>
                </td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td colspan="3">
                    <textarea id="id_address" name="address">{{ volunteer.address }}</textarea>
                </td>
            </tr>
            <tr>
                <th>Date de naissance</th>
                <td>
                    <input type="text" id="id_birthday_day" maxlength="2" size="2"
                           name="birthday_day" value='{{ volunteer.birthday|date:"d" }}'>
                    <input type="text" id="id_birthday_month" maxlength="2" size="2"
                           name="birthday_month" value='{{ volunteer.birthday|date:"m" }}'>
                    <input type="text" id="id_birthday_year" maxlength="4" size="4"
                           name="birthday_year" value='{{ volunteer.birthday|date:"Y" }}'>
                </td>
                <th>Lieu de naissance</th>
                <td>
                    <input type="text" id="id_birth_place" name="birth_place"
                           maxlength="100" value='{{ volunteer.birth_place }}'>
                </td>
            </tr>
            <tr>
                <th>Numéro de sécu</th>
                <td>
                    <input type="text" id="id_social_security_number" maxlength="15"
                           name="social_security_number" value="{% if volunteer.social_security_number %}{{ volunteer.social_security_number }}{% endif %}">
                </td>
                <th>Première inscription</th>
                <td>
                    <input type="text" disabled class="disabled" name="inscription_date"
                           value='{{ volunteer.inscription_date|date:"d F Y" }}'>
                </td>
            </tr>
            <tr>
                <th>Commentaires</th>
                <td colspan="3">
                    <textarea id="id_comments" name="comments">{{ volunteer.comments }}</textarea>
                </td>
            </tr>
            <tr>
                <th>Photographie</th>
                <td colspan="3">
                    {{ form.avatar }}<br>
                    <input type="checkbox" id="id_delete_avatar" name="delete_avatar"><i>Supprimer la photo actuelle?</i>
                </td>
            </tr>
        </table>
        <p class="required">* Les champs marqués en <span>rouge</span> sont obligatoires.</p>
        <input type="submit" value="Enregistrer">
    </form>
{% endblock %}

{% block navigation %}
    <ul>
        {% if volunteer %}
            <li><a href="{{ volunteer.get_absolute_url }}" title="">Revenir à la fiche de ce bénévole.</a></li>
        {% else %}
            <li><a href="{{ settings.OPENVOLUNTEER_WEB_ROOT }}/volunteer/" title="">Rechercher un bénévole</a></li>
        {% endif %}
    </ul>
{% endblock %}